### ISSUE TITLE
Review Workshops FAQ

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#105]
Preview FAQ: https://carp-new-website.netlify.app/workshops/workshops-faq/

This FAQ is built from a document from 2020-2022.  It has a lot of outdated language (referring to supporting/experienced Instructors, Regional Coordinators, etc.).  It also has a lot of repetitive language which I would recommend consolidating as otherwise it will be very difficult to maintain.  

This should also be considered along with #88 as the FAQ should not repeat language that is in other places, but rather should refer to that content.

Lastly, noting here that because this document seems to need a lot of work, I have not updated any links, so please disregard any broken links.  I will take care of that after content has been updated. 

Displaying the Table of Contents at the top is optional - let me know whether you want it.

**Comment by maneesha** [comment]
@sheraaronhurt  Yes, I can work on bringing over the current FAQ page.  I will tag you again for review.

**Comment by maneesha** [comment]
@sheraaronhurt @danielle06 The workshops FAQ has been replaced with what is on our current site.  See https://carp-new-website.netlify.app/workshops/workshops-faq/

Note this still contains outdated information, like referencing Regional Coordinators, CT members old titles, etc.

Many links will also need to be updated, but we should do that after you finish the general workshops page.

**Comment by sheraaronhurt** [comment]
@maneesha thanks so much. I have reviewed and this is good for now. When we finish we will make the update to all of the content.
