### ISSUE TITLE
Workshops page still has filler text

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/new-website#109]
While reviewing pages outside of my normal areas (as requested!), I found that https://carp-new-website.netlify.app/workshops/ still has some filler text in the "Why The Carpentries workshops" section. 

<img width="878" alt="Screenshot 2024-09-19 at 3 37 27 PM" src="https://github.com/user-attachments/assets/6fe430b1-b55b-49e0-95f6-0524d5a97ada">

**Comment by maneesha** [comment]
This is being fixed with #128
