### ISSUE TITLE
Descriptions of our curricula link goes to empty header

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/new-website#110]
On the [workshops page](https://carp-new-website.netlify.app/workshops/), the sentence "To help you decide which Lesson Program is best for your audience, please read the [descriptions of our curricula](https://carp-new-website.netlify.app/workshops/#)." links to an empty header that returns user to the top of the current page.

**Comment by maneesha** [comment]
I need to fix this link.

**Comment by maneesha** [comment]
Fixed with #126
