### ISSUE TITLE
Inconsistent button text formatting on workshops page

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/new-website#111]
On the [workshops page](https://carp-new-website.netlify.app/workshops/), the two buttons have text that is differently formatted from each other. I recommend keeping the top button text as is and changing the second button text to "Request a workshop" (note not capitalized and "Carpentries" removed). 
<img width="479" alt="Screenshot 2024-09-19 at 3 40 13 PM" src="https://github.com/user-attachments/assets/94c238ef-fdc1-4210-9605-38ee08651989">

**Comment by maneesha** [comment]
Assigning to @OscarSiba  for feedback about general styling.

**Comment by OscarSiba** [comment]
I agree with this formatting suggestion. Maneesha, are you able to apply this change this directly to the templates or do I need to check every button on every page?

**Comment by maneesha** [comment]
The suggestion from @ErinBecker above applies to text on this button on this page. Other buttons on other pages may have other text.  It is up to you whether you would like to adjust language on other pages.

**Comment by maneesha** [comment]
@OscarSiba  Please review https://carp-new-website.netlify.app/workshops/
If it looks good, you can close this issue.  Otherwise please leave any other feedback here.

**Comment by OscarSiba** [comment]
Can we please also change the text in buttons on this page to adhere to the same format? https://carp-new-website.netlify.app/workshops/host-workshop/

**Comment by maneesha** [comment]
@OscarSiba That change has been made. Please review.
Close this issue if it looks good, or leave any other feedback here.
