### ISSUE TITLE
Shorten "Contact" section on Workshops page

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/new-website#112]
On the [Workshops page](https://carp-new-website.netlify.app/workshops/), the Contact section has the following text: 

Have Questions? Please consult our [Workshops FAQ](https://carp-new-website.netlify.app/workshops/workshops-faq) or contact the Workshops and Instruction Team. Our Team is ready to answer any additional questions you may have. To reach us, or to find out more, please send us an email to workshops@carpentrires.org.

I recommend shortening to: 

Have Questions? Please consult our [Workshops FAQ](https://carp-new-website.netlify.app/workshops/workshops-faq) or contact our team at workshops@carpentries.org.

**Note typo in email address**

**Comment by ErinBecker** [comment]
For consistency, I also recommend shortening the Contact section on the other pages to match the above recommendation. E.g. 

https://carp-new-website.netlify.app/instructor-training/

**Comment by maneesha** [comment]
Assigning this to @OscarSiba  as a general communications question.

**Comment by maneesha** [comment]
@OscarSiba This has been fixed. Can you review? If it looks good, you can close this issue.

**Comment by OscarSiba** [comment]
This is good, thank you Maneesha.

**Comment by sheraaronhurt** [comment]
@maneesha they can email instructor.training@carpentries.org
