### ISSUE TITLE
Rephrase "Trainer" >> "Instructor Trainer"

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/new-website#113]
I think the first section of the [Trainer Training page](https://carp-new-website.netlify.app/trainer-training/) wasn't intended to appear on the website. @sheraaronhurt - could you please confirm?

<img width="654" alt="Screenshot 2024-09-19 at 3 47 29 PM" src="https://github.com/user-attachments/assets/8e37c4d1-6736-4ea3-8cf4-c46182d6fd57">

**Comment by maneesha** [comment]
Thanks for catching that placeholder text @ErinBecker 
I have removed it.

**Comment by sheraaronhurt** [comment]
Also @maneesha  can we title this page Instructor Trainer Training?

**Comment by sheraaronhurt** [comment]
Yes @maneesha please change everywhere

**Comment by maneesha** [comment]
@sheraaronhurt This is fixed - I think I caught everything! If this looks good to you, you can close this issue.

**Comment by sheraaronhurt** [comment]
Thanks @maneesha LGTM! closing.
