### ISSUE TITLE
Updates to "Get involved" page 

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#133]
I have worked through the updates @elletjies  put in for the [Get Involved page](https://carp-new-website.netlify.app/community/get-involved/).  I have put in updated links when possible, and placeholder links for us to come back to.  I still have a few questions:

* The list of bullets at the top seems a bit off to me, with "Overseeing the training and certification of Instructors" as a separate bullet, and the others nested under the heading "Maintaining global communities of practice."  It would make more sense to me to have everything nested under that bullet.
* Something to come back to later -  I think there is some info that would duplicate handbook content.  The Handbook is supposed to list how to get involved, communications channels, etc.  Opening this issue to come back to and be sure we are not duplicating any content.

**Comment by elletjies** [comment]
@maneesha thanks - lets see what nesting the bullets look like.

**Comment by maneesha** [comment]
I've nested the bullets so they are better aligned.

@elletjies  Another suggestion - we have the link in the bulleted list at the top for "Community Sessions"  which takes you to the bottom of the page and then directs you to the community calendar. Perhaps that could link directly to the community calendar? (instead of the intermediate step of going to the bottom of that page?)
