### ISSUE TITLE
Impact page review

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/new-website#138]
Notes from a review of https://carp-new-website.netlify.app/about-us/impact/

* [x] I would prefer not to have the "scare quotes" around "Always Learning" but accept that this is personal preference and may be a style choice.
* [x] The most recent Annual report listed is from 2021: can we include those for the past couple of years as well?
* [x] The heading "Referencing Annual Reports" does not match well to the sentences that follow: when I saw the heading, I exected the content beneath to tell me how I should cite the reports if I use them. (Info about the license of the report is similar but not the same, as most people are likely to want to cite the existing report rather and adapt/re-use it elsewhere.) Is citation information in the reports themselves? If not, could we add something to that effect in this section, e.g. "When referring to one of our annual reports, please cite the document as described on the Zenodo entry of the report."
* [x] In "Measuring the impact of our workshops a training", adjust to refer to both Instructor Training and CLDT, i.e. "We conduct pre- and post-workshop surveys for Carpentries Workshops & Training Events." We cannot provide a preview of the pre- and post-training surveys for CLDT just yet, but I plan to migrate it into TypeForm soon.
* [x] A "y" is missing off the end of the "Preview the Long Term Impact Surve**y**" button.

**Comment by maneesha** [comment]
The issues in the last two bullets have been fixed.

I will be updating all of the Annual Reports separately.

I would defer to @OscarSiba for the questions about the quotes and about referencing annual reports.

**Comment by OscarSiba** [comment]
Please remove the quotes around "Always Learning" as suggested by Toby. 

Please change heading "Referencing Annual Reports" to "Annual Reports License". Also, please hyperlink "Creative Commons Attribution 4.0" with this URL: https://creativecommons.org/licenses/by/4.0/legalcode

**Comment by maneesha** [comment]
Thanks @OscarSiba -- I can make those changes.  Should the capitalization (Always Learning) remain?

**Comment by OscarSiba** [comment]
Please keep that capitalized, but perhaps also bolded or italicized to indicate its one of our core values. Better yet, if possible, also link it to the section of our core values to drive the point home.

**Comment by OscarSiba** [comment]
Reviewed and closing this issue.
