### ISSUE TITLE
Our Team page review

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/new-website#140]
Notes from a review of https://carp-new-website.netlify.app/about-us/team/

* [x] I would like an extra sentence in the introduction to this page, describing what the Core Team does and how that relates to the activities of the community. E.g. "The Core Team facilitates the activities of our community, ensuring that the organisation meets its strategic goals and fulfills its mission."
* [x] I would like more whitespace between the bottom of the circular profile pictures and the text of the members' names.
* [x] Is it appropriate/recommended to include links to team members' Twitter/X profiles, since The Carpentries intentionally moved away from that platform some time ago? I feel that Mastodon/BlueSky would be more appropriate, or we could leave social media profiles off the list altogether...
* [ ] #199

**Comment by maneesha** [comment]
The question about whitespace and the alignment of the profiles is something we will address after this launch.

@ErinBecker Can you advise on Toby's recommendation for the intro text? 

@OscarSiba Can you advise about linking to Twitter/Mastodon/other social media?

**Comment by OscarSiba** [comment]
I think we should add Mastodon accounts for CT members that have accounts:

@angeliquetrusler@mastodon.social 
Rob: @froggleston@mstdn.science  
@oscarsibabalwe@mastodon.social 
@drkariljordan@mastodon.social 

However, I don't think we should remove Twitter handles. We moved away from Twitter as an organisation, but not as individuals, and many members of our community are still on the platform, and I don't think we need to conceal that some individual CT members are also still active.

**Comment by maneesha** [comment]
@OscarSiba I think we can add mastodon. Can you share how URLs get rendered from a username?

**Comment by OscarSiba** [comment]
Please see below:

https://mastodon.social/@drkariljordan
https://mastodon.social/@oscarsibabalwe
https://mastodon.social/@angeliquetrusler
Rob: https://mstdn.science/@froggleston

**Comment by ErinBecker** [comment]
I approve Toby's suggestion for the intro text! Thanks @tobyhodges!

**Comment by maneesha** [comment]
The first three bullets have been addressed.
#198 adds the intro text and Mastodon links, noting @OscarSiba  has recommended keeping Twitter/X.

A new issue  (#198) is opened to consider spacing and alignment of profiles.
