### ISSUE TITLE
Contact Us page review

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/new-website#141]
Notes from review of https://carp-new-website.netlify.app/about-us/contact/

* Duplicated "you" in first sentence "If you **you** would [...]"
* Should we add "Curriculum enquiries: curriculum@carpentries.org" to the list, or do you want only addresses that route messages into Help Scout?

**Comment by maneesha** [comment]
@tobyhodges  If you would like to see "Curriculum enquiries" listed, we can add that. Please let me know.  It's not a question about Helpscout.

**Comment by tobyhodges** [comment]
Ok, great. Then yes please add it to the list 🙌

**Comment by maneesha** [comment]
@tobyhodges  please review this page and close this issue if it looks good to you.  https://carp-new-website.netlify.app/about-us/contact/
