### ISSUE TITLE
"nonprofit" vs "non-profit"

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/new-website#142]
On https://carp-new-website.netlify.app/about-us/ we say that we are "a mission-driven, registered 501(c)(3) nonprofit project", while on https://carp-new-website.netlify.app/about-us/governance/ we say that we are "a fiscally sponsored project of [Community Initiatives](https://communityinitiatives.org/), a registered 501(c)(3) non-profit based in California, USA." This raises two points for me:

1. Are these both true? Or should we choose one over the other?
2. Should we hyphenate or not (i.e. "non-profit" or "nonprofit"?)

**Comment by maneesha** [comment]
@ErinBecker  Can you answer the first question or should we wait for Kari? 

I will defer to @OscarSiba on the hyphenation styling.

**Comment by ErinBecker** [comment]
We will still be a fiscally sponsored project of CI when the new website goes live, so please retain that language ("a fiscally sponsored project of [Community Initiatives](https://communityinitiatives.org/), a registered 501(c)(3) non-profit based in California, USA.")

**Comment by maneesha** [comment]
The language about FSP status has been updated to be consistent with our current status.
I will leave this issue open for the small detail about the hyphenated style.

**Comment by OscarSiba** [comment]
Please hyphenate "non-profit."
