### ISSUE TITLE
Governance page review

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/new-website#143]
Notes from review of https://carp-new-website.netlify.app/about-us/governance/

- [x] The link leads to a 404 error in "You will find our past governance members on the [Carpentries Governance History](https://carp-new-website.netlify.app/governance-history/) page."
- [x] The email address link in "Contact the Board by [sending an email](https://carp-new-website.netlify.app/about-us/governance/board@carpentries.org) needs a `mailto:` protocol to be added.
- [x] The link "[The Carpentries Bylaws can be found here](https://carp-new-website.netlify.app/files/exec_council/carpentries_inc_bylaws.pdf)." leads to a 404 error.

**Comment by maneesha** [comment]
Thanks @tobyhodges

**Comment by maneesha** [comment]
The first two items have been addressed. See https://carp-new-website.netlify.app/about-us/governance/

I am working on  updating the link to bylaws and other documentation.

**Comment by maneesha** [comment]
Link to bylaws has been fixed.
