### ISSUE TITLE
Review 404 page 

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#161]
@OscarSiba This is what the 404 page would look like, based on your recommendations.  Please share any comments here.  
Please use this url and not the usual one:
https://deploy-preview-160--carp-new-website.netlify.app/asdfg

**Comment by OscarSiba** [comment]
Please edit the "ask about it" text to read "ask us about it".

**Comment by maneesha** [comment]
@OscarSiba  Please review changes here: 
https://carp-new-website.netlify.app/sadfasdf

If this looks good to you, you can close this issue.  Otherwise, please share any other feedback here.
