### ISSUE TITLE
Review Search page

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#162]
@OscarSiba This is what the Search page would look like, based on your recommendations. Please share any comments here.
Please use this url and not the usual one:
https://deploy-preview-160--carp-new-website.netlify.app/search

Note the search page will not acutally be functional. You are reviewing only for the layout/design.

**Comment by OscarSiba** [comment]
Please delete "Enter search term and hit enter" - that is only supposed to be the faint text inside the search bar/box.

**Comment by maneesha** [comment]
@OscarSiba  The change has been made.  See 
https://carp-new-website.netlify.app/search/

If this looks good to you, you can close this issue. 
Otherwise please share any other feedback.
