### ISSUE TITLE
Membership FAQ

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#171]
The Membership FAQ was missed in the earlier reviews.  It had placeholder text.  I have updated it with the content of our current membership page.

Not all links have been updated as many links are going to change along the way.  Please share any feedback about content. I will fix links later. 

See https://carp-new-website.netlify.app/support/membership/membership-faq/

**Comment by maneesha** [comment]
@elletjies @ErinBecker Also note  that if you're ok keeping the FAQ as is for now, no further review is required. We can do another review later.  I will make sure all the links are up to date.

**Comment by elletjies** [comment]
@maneesha we have been keeping the FAQ's up to date, so if @ErinBecker agrees I am good to keep it as is.

**Comment by ErinBecker** [comment]
I approve of keeping it as is!
