### ISSUE TITLE
Review Community Lessons table 

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#175]
See notes from @tobyhodges in slack about how this is currently built:

> https://github.com/carpentries/reactables/blob/main/R/lesson_table.R based on info from https://feeds.carpentries.org/community_lessons.json
> 
> Technically the script I linked to above is run by another one (https://github.com/carpentries/reactables/blob/main/script.R) in a scheduled Actions workflow (https://github.com/carpentries/reactables/blob/main/.github/workflows/build_table.yml)

**Comment by maneesha** [comment]
This has been set up.  See https://carp-new-website.netlify.app/lesson-development/community-lessons/

Note we will have to consider search/filter options after this website launches.

**Comment by tobyhodges** [comment]
Overall this look good. A few comments from review:

* Accepting that it is not possible to implement them before launch, including search/filter options will certainly make the tables more usable. Please let me know if there is anything I can do to help get this implemented. I would defer to those with more expertise in style/layout/design, but I think some additional colour on the tables might help too, e.g. to distinguish between the `help wanted` and `good first issue` labels, and the life cycle stages of the lessons listed.
* Presumably, most visitors do not scroll down far enough to encounter the information at the end of https://carp-new-website.netlify.app/lesson-development/community-lessons/ and it is not clearly signposted from the introductory text. I should have noticed this when drafting the content, sorry! Please could we add an additional paragraph before the _Browse Community Developed Lessons_ heading?

> `[More information about The Carpentries Incubator, The Carpentries Lab, and how this table is built is available at the end of this page](#the-carpentries-incubator).`

(Noting that the info about the Incubator and Lab will probably be removed when the new _Curriculum Development Ecosystem_ handbook page is published.)

**Comment by maneesha** [comment]
@tobyhodges Agreed that search, filter, and styling of tables should be a priority after the initial launch.  

I will make the change to the text as you noted in your second bullet.

**Comment by maneesha** [comment]
@tobyhodges An anchor link has been added to direct users to the info at the bottom of the page.

Searching/filtering the table is something we would address at the theme level, so an issue has been opened [in that repo](https://github.com/carpentries/carpentries-hugo-theme/issues/53).
