### ISSUE TITLE
Overall site review: "Impact" and "Financials" pages

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/new-website#192]
---

Having reviewed the CT's updates to the website, and keeping in mind the conventions set out in our [style guide](https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html), as well as to achieve consistency across the various website pages, please make the following changes to this page: https://carp-new-website.netlify.app/about-us/impact/ 

**Introduction**
- [x] Please revise this sentence to read as follows: "We embody the growth mindset we teach **by** using data..."

**Assessment**
- [x] Please capitalise the initials in "(instructor training)".

And then to the following page: https://carp-new-website.netlify.app/about-us/financials/

**Financial Reports**
- [x] In the second sentence, please make "Annual Report" plural and then hyperlink it only [Annual Reports], and not the "our". 

---

**Comment by maneesha** [comment]
Addressed with #202
