### ISSUE TITLE
Overall site review: "Contact us" page

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/new-website#194]
---

The changes here pertain to this page: https://carp-new-website.netlify.app/about-us/contact/

**By email**
- [x] For uniformity with the other email contacts please add "enquiries" after Code of Conduct. 

**On social media**
Please spell as "YouTube" and "LinkedIn" (capital "T" and "I". 

---

**Comment by maneesha** [comment]
Addressed with #203
