### ISSUE TITLE
Deprecate Online Workshop Recommendations?

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#209]
@sheraaronhurt  I think we talked about this but I want to make sure.  Are we planning to deprecate the Online Workshop Recommendations?  See https://carpentries.org/online-workshop-recommendations/

**Comment by sheraaronhurt** [comment]
@maneesha we will discuss this during our WIT call today. I will come back and update

**Comment by sheraaronhurt** [comment]
Hey @maneesha we can link to the Online Recommendations Tip Sheet  https://zenodo.org/records/13940453

**Comment by maneesha** [comment]
Thanks @sheraaronhurt 
What page should we link to this from?

**Comment by sheraaronhurt** [comment]
Hey @maneesha let's link should actually be in the handbook and not the website. Once we start working on the handbook I will be sure to add the link.

**Comment by maneesha** [comment]
Closing this as @sheraaronhurt  has noted above this should be in the handbook, not the website.
