### ISSUE TITLE
Style changes to the Membership page

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/new-website#210]
---

**Membership**: https://carp-new-website.netlify.app/support/membership/ 

- [x] Under "Why Membership?", please make all the first sentences on that list bold. 
- [x] Under "Why Membership?", in the third point on that list, please put a space between the first and second sentence. 
- [x] Please delete the subheading "Selecting A Membership Level". This should also remove it from appearing on the sidebar menu. 
- [x] Under "Membership Levels", please spell "customizable" and "customisable".
- [x] Please make "[View our current pricing tiers](https://carp-new-website.netlify.app/support/pricing/)" one of those blue hyperlinked action buttons.
- [x] Each line in listed under "In addition to the benefits above, all Memberships include" must in a full stop. 

**Membership FAQ** https://carp-new-website.netlify.app/support/membership/membership-faq/

- [ ] #221
- [x] Under the question "What are the standard membership packages you offer?" please spell "self-organised" as "Self-Organised".
- [x] Under the question "Which membership should I purchase?" please make the type of memberships at the beginning of each sentence (Bronze membership, Silver and Gold memberships, etc.) bold. 
- [x] Under the same question, in the Bronze membership category, please spell capitalise the initial letters in "instructor training". 
- [x] Under the question "Are any discounts available?", please delete the comma in the following sentence: "Members can choose whether they would like to have the Trainer discount applied as a monetary discount, or as added benefits."
- [x] Under the same question, please revise this sentence as follows: "This discount is available at any membership level, for each Trainer who has participated in the following up to 1 year prior to renewal:"
- [x] Then please add a full stop at the end of the bulleted point. 
- [x]  Under the question "How do your workshops run?" please note that the link to "[a la carte](https://carp-new-website.netlify.app/membership/#a-la-carte-pricing)" leads to the 404 error page. 
- [x] Under the same question, please note also that links to our lesson programs lead to the old lesson program sites and not the new ones. 
- [x] Under the same question, please note also that the link to the [curricula page](https://carp-new-website.netlify.app/workshops-curricula/) leads to the 404 error page. 
- [x] Under the question "What if I want to run more Centrally-Organised workshops than my agreement allows?" the link to the pricing page leads to the 404 error page. 
- [x] "How should I select individuals to be trained as Instructors?" - please use "s" instead of "z" for "Organisations" in [Information for Member Organizations](https://carp-new-website.netlify.app/support/membership).
- [x] "What if I want to train more people at my site than my agreement allows?" - the link to the pricing page leads to the 404 error page. 
- [x] "Can individuals get trained to become Instructors outside of the context of institutional membership?" - the link to "[a la carte](https://carp-new-website.netlify.app/membership/#a-la-carte-pricing)" leads to the 404 error page. 
- [x] Under "Contact us" please remove the "..." at the beginning of each of those listed contacts, and capitalise the first letter of each line. Further, please delete "Contact" before listing each email address. Each line must have a bullet at the beginning, and a colon at the end, before listing the email address. It should not be bolded. Basically, it must follow the same format as our [main "Contact us" page](https://carp-new-website.netlify.app/about-us/contact/). 

---

**Comment by maneesha** [comment]
Everything here has been addressed with #220 except for the membership FAQ which has been moved to issue #221
