### ISSUE TITLE
Etherpad of etherpads for Community Events

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/new-website#213]
---

**Community Events**: https://carp-new-website.netlify.app/community/events/

The [Etherpad](https://pad.carpentries.org/pad-of-pads) that is linked to our community calendar needs to be updated. CET will co-work to update, and then link the updated pad to this issue and reassign issue to Maneesha to update on the new website. 

---

**Comment by elletjies** [comment]
@OscarSiba I think it is best just to update the pad - not to create a new one.

**Comment by maneesha** [comment]
Agreed with @elletjies  - the link to the pad-of-pads should not change, but the content should be updated. Closing this issue here.
