### ISSUE TITLE
Style changes/Edits to the "Get Involved" page

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/new-website#215]
---
Get Involved: https://carp-new-website.netlify.app/community/get-involved/

- [ ] The information on this page is a repetition of information that is on other pages throughout the website, as well as information that will probably be in the Handbook and is better suited to be in the Handbooks. Is there a specific reason to keep this here? CC @elletjies for input. 

- [ ] I would recommend only keeping the following information:

You can get involved with The Carpentries by volunteering in one of our [community roles](https://carp-new-website.netlify.app/community/). To find out more about the duties and benefits of volunteering in these roles, as well as how to be onboarded onto and offboarded from these roles, please visit our [Handbook](https://carpentries-beta-handbook-preview.netlify.app/).
 
We also keep our community strong and connected through meetups (virtual and in-person) and interest-specific mailing lists.

[Regional Subcommunities](LINK TO THE SUBHEADING BELOW]
[CarpentryCon](https://carp-new-website.netlify.app/community/get-involved/#carpentrycon) - our in-person meetup for our global community.
[CarpentryConnects](https://carp-new-website.netlify.app/community/get-involved/#carpentryconnects) - regional community conferences organised by local community members in The Carpentries.
[Community sessions](https://carp-new-website.netlify.app/community/events/)
[Mailing lists](https://carpentries.topicbox.com/latest)

**Regional Subcommunities**
For a full listing of Carpentries subcommunities, please visit our [subcommunity registry](https://carp-new-website.netlify.app/community/get-connected/#subcommunities).

**CarpentryCon**
The Carpentries hosts [CarpentryCon](http://www.carpentrycon.org/), a community-organised meeting for our global community.

[CarpentryCon 2018](https://2018.carpentrycon.org/) was held from 30 May to 1 June 2018 in Dublin, Ireland.
[CarpentryCon 2020](https://2020.carpentrycon.org/) was held between July and August 2020 as a seven week online event.
[CarpentryCon 2022](https://2022.carpentrycon.org/) was held 1-12 August 2022 as an online event.
If you are interested in helping to organise the next CarpentryCon, contact us at [community@carpentries.org](mailto:community@carpentries.org).

**CarpentryConnects**
CarpentryConnects are community convenings, organised to bring together community members of The Carpentries that are in close proximity geographically for knowledge exchange, collaboration, and networking. [The CarpentryConnect Planning Kit](https://carpentryconnect.org/) provides checklists, templates, recommendations for best practices and resources to serve as guides in planning and carrying out CarpentryConnect events.

Here is a list of all CarpentryConnect events held in the past: [carpentryconnect.org/case-studies/](https://carpentryconnect.org/case-studies/)
---

**Comment by maneesha** [comment]
Removing myself as assignee until the CET has decided what should be here.

**Comment by elletjies** [comment]
Thanks, @OscarSiba I agree and have made the necessary amendments in this https://github.com/carpentries/new-website/pull/250

**Comment by maneesha** [comment]
#250 has been merged.
