### ISSUE TITLE
Style changes to "Workshops" pages

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/new-website#223]
---

**Workshops**: https://carp-new-website.netlify.app/workshops/

- [x] Please move the "Request a workshop" blue button from the bottom up to the end of the "Why The Carpentries workshops" section. 

**Host a Workshop**: https://carp-new-website.netlify.app/workshops/host-workshop/

- [x] Under the "Host a workshop" subheading, in the second bullet point, please hyperlink "upcoming workshops page" to that page. 
- [x] Under the "Host a workshop" subheading, in the third bullet point, please hyperlink " impact of Carpentries workshops" and link to this page: https://carp-new-website.netlify.app/about-us/impact/#other-impact-reports
- [x] Under "What to know before requesting a Centrally-Organised Workshop" please add a full stop after every sentence on that list. 
- [x] Under "What to Expect After Requesting a Workshop" please change "Date confirmed" to "Date confirmation".
- [x] Under the same heading, in the "Instructors connected" sentence, please remove "..." towards the end of the sentence: "workshop so that ….can be discussed".
- [x] Where is the [Workshop Host Checklist](https://carp-new-website.netlify.app/workshops/host-workshop/#). supposed to lead to? 
- [x] Under "Travel Expenses for Instructors" please spell "Host" with small letters. 

**Workshops FAQ**: https://carp-new-website.netlify.app/workshops/workshops-faq/

- [x] Please present all these questions and answers in the accordion style, each accordion separated by the main headings.
- [x] "Why is my workshop not listed on the carpentries.org webpage?" - please spell out 3 - i.e. "three things"
- [x] "If I am teaching a Data Carpentry Genomics workshop, how many AWS Instances will be provided and when will we receive them?" - please spell out all the numbers that are under 9: In this case, "2-3 weeks" as "two to three weeks"; "Approximately 1 week prior" as "one"; " Approximately 3 days" as "three".  
- [x] "If I am teaching a Data Carpentry Genomics workshop, how many AWS Instances will be provided and when will we receive them?" - please spell "Hosts" with small h. 
- [x] "How do I access the survey results?" - please spell out the numbers in 1-2 weeks, i.e. "one to two weeks" 
- [x] "How much does a workshop cost?" - please replace the "Please visit our [website](https://carp-new-website.netlify.app/workshops/#workshop-cost) for more information." with "Please visit our [Pricing page](https://carp-new-website.netlify.app/support/pricing/) for more information.
- [x] #231
- [x] "Who can be a Helper and what do they contribute to the workshop?" - please spell Helper with a small h. 
- [x] "Are Helpers reimbursed for travel?" - in this heading and in the first sentence, please spell Helper with a small h. 
- [x] "As an Instructor, will I still get credit for a workshop if the host cancelled?" - please replace "resign" with "withdraw". 
- [x] "How soon can I request a Carpentries workshop?" - please spell out the numbers: "2-3 months", "less than 2 months". 
- [x] For the same question, please also spell "finalized" with "s" and not "z". 
- [x] "My currency is not USD, will I get invoiced in USD or my local currency?" - please spell "organization"  with "s" and not "z".
- [x] For the same question, please replace "Business Team" with "Management Team."
- [x] "Is there a fee for running a Self-Organised workshop?" - please spell instructor with capital "I".
- [x] For the same question, also replace the link in "Visit our [website](https://carp-new-website.netlify.app/workshops/#workshop-organising)" with this one instead: https://carp-new-website.netlify.app/workshops/host-workshop/
- [x] "How do I inform you I am running a Self-Organised workshop?" - the link to "[add your workshop to our website](https://carp-new-website.netlify.app/upcoming_workshops/)" is broken. Please replace it with: https://carp-new-website.netlify.app/workshops/upcoming-workshops/
- [x] "If I need help recruiting Instructors and/or Helpers for a Self-Organised workshop, what are my options?" - in this title and in the text below it, please spell Helpers with a small h. 
- [x] For the same question, please spell " slack" with capital S. 
- [x] "I have never taught an online workshop, where should I begin?" - the link in the answer to this leads to content on the old site. 
- [x] "Does the workshop have to be 2 full days?" - in this title and text below please spell out "two", as well as "four".
- [x] "Will I be provided with a Zoom room to run my online workshop?" - please spell instructor with a capital "I". 
- [x] And also spell "organizers" with an "s" instead if a "z". 
- [x] Note also, that the link to [Recommendations for Teaching Carpentries Workshops Online](https://carp-new-website.netlify.app/online-workshop-recommendations/) is broken. 
- [x] "How many Instructors are needed to teach the workshop?" - the link to [instruction roles](https://carp-new-website.netlify.app/online-workshop-recommendations/#instructional-roles) for a workshop is broken.
- [x] "What are the roles of everyone participating in a workshop?" - please spell Curricula with small c. 
- [x] See issue @223
- [x] "What is the difference between a Centrally-Organised workshop and a Self-Organised workshop?" - is the link to [administrative fee](https://carp-new-website.netlify.app/workshops/#workshop-cost) supposed to be the Pricing page? The link to [certified Instructors](https://carp-new-website.netlify.app/instructors/) is also broken.
- [x] Also on the same question, please spell instructor with capital "I"
- [x] "How do I get survey data/links for previous workshops?" - please spell instructor with capital "I"
- [x] "Are there email templates available for me to locate helpers?" - please spell instructor with capital "I"
- [x] #232
- [x] "Can I charge Learners a fee to attend a workshop I host?" - please spell Host with a small h. 
- [x] "Can I pay Instructors a stipend?" - please spell Host with a small h, and  instructor with capital "I". 
- [x] Also, please note that the link to [donation](https://carp-new-website.netlify.app/donate/) is broken. 
- [x] Under "Further Resources" please say, "Visit" instead "See" to avoid ableist language. 
- [x] Please also note that the link to [Membership FAQ page](https://carp-new-website.netlify.app/member_faq/) is broken. 

---

**Comment by maneesha** [comment]
@OscarSiba  you noted above in one place to spell "Host" with lowercase letters.  Everywhere else it is uppercase.  Is it only this instance that should be lowercase?

**Comment by maneesha** [comment]
Noting here that the Host Checklist may be a Handbook section. I will keep this issue open to come back to that item.

**Comment by maneesha** [comment]
Points that need review by the WIT are being turned in to new issues.

**Comment by maneesha** [comment]
Summary of remaining tasks:

* Whether to capitalise workshop Host/host
* Linking to resources for online workshops
* Linking to Host Checklists

**Comment by maneesha** [comment]
@OscarSiba please advise about whether "host" should consistently be capital/lowercase.  I'll follow up on the other remaining questions.

**Comment by OscarSiba** [comment]
Hi @maneesha. My understanding is that roles such as host, organiser, and helper (uncertified roles, and roles for which there is no onboarding process) should be in small letters unless at the start of a sentence. There has been inconsistency about this in the past, and throughout our comms, but I think we ought to tighten on this convention as we become more focused on badging efforts. I will also just ping @elletjies to please confirm.

**Comment by elletjies** [comment]
In my opinion, all should be capitalised, one role is not more important than another. However, if it has been the contention as Oscar has mentioned I will be ok with this (something we need to discuss within the CET)

**Comment by maneesha** [comment]
Noting here that my question was about whether we should always have host in lowercase, as the comments from @OscarSiba across our materials have suggested to have "host" lowercase in some but not all cases.  

I went back to review our [style guide](https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html#capital-letters-and-capitalisation), and it seems "host" should always be lowercase.  I will make this change.

**Comment by maneesha** [comment]
For now, the online workshop recs and the workshop host checklist will link to resources in the existing handbook.  We will consider additional changes when we launch the handbook.

**Comment by maneesha** [comment]
These remaining fixes are addressed with #248
