### ISSUE TITLE
Style changes to "Collaborative Lesson Development" pages

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/new-website#237]
---
**Collaborative Lesson Development**: https://carp-new-website.netlify.app/lesson-development/

- [ ] In the introductory paragraph, the link to [Carpentries Collaborative Lesson Development Training](https://carp-new-website.netlify.app/lesson-development/#about-the-training) links to the page that it's on... Was this meant to link to the curriculum? In that case, this: https://carpentries.github.io/lesson-development-training/ However, there is a link to the curriculum further down, so perhaps we just remove this hyperlink here completely. CC-ing @tobyhodges for input. 
- [ ] Under "Target audience" I think we need to mention that ideally the training requires 2 or more people to register to collaborate together to develop the lesson, and also that at least one person in the lesson team must have attended The Carpentries Instructor Training. I know this is expanded on in the FAQ, but it also needs to be here as it is key information. CC-ing @tobyhodges for input. 
- [x] Under "What will you learn?", for the second bulleted list set ("After attending this training, participants will be able to"), please put full stops at the end of each sentence. 
- [x] In that same list, please remove the dash from this sentence: "explain how considerations of cognitive load should influence - the pacing, length, and organisation of a lesson"
- [x] Please do the same for this sentence: "use best practices to configure and maintain accessible and - usable lesson repositories that are readily available for collaboration"
- [ ] Under "Training structure" is there a way to reducing the size of the image so that its right side doesn't get obscured under the sidebar menu when we scroll up/down. See screenshot below:
![image](https://github.com/user-attachments/assets/e466b293-320a-4a36-a14a-7581b09cc811)

- [x] Under "Contact Us" please use the following instead: Have Questions? Please consult our [Collaborative Lesson Development FAQ](https://carp-new-website.netlify.app/lesson-development/cldt-faq/) or contact our team at [curriculum@carpentries.org](mailto:curriculum@carpentries.org).

**Collaborative Lesson Development FAQ**: https://carp-new-website.netlify.app/lesson-development/cldt-faq/

- [ ] "Who teaches Collaborative Lesson Development Training?" - the mention to "a multi-week program of Trainer Training" needs to specify which Trainers we are referring to. Is it Lesson Developer Trainer Trainers or some other type of trainers? Cc-ing @tobyhodges to clarify. 
- [ ] "What options exist for a lesson after the training?" - the link to [consideration as a new lesson program](https://carp-new-website.netlify.app/lesson-development/cldt-faq/#) links to the page that it is on. I suspect it was meant to lead to this page in the Handbook: https://docs.carpentries.org/topic_folders/governance/lesson-program-policy.html#lesson-program-incubation-roadmap  CC-ing @tobyhodges for input. 

**Community Lessons**: https://carp-new-website.netlify.app/lesson-development/community-lessons/

- [x] Please remove the hyperlink from [The Carpentries Incubator](https://carp-new-website.netlify.app/lesson-development/community-lessons/#the-carpentries-incubator) is for...
- [x] Please also remove hyperlink from [The Carpentries Lab](https://carp-new-website.netlify.app/lesson-development/community-lessons/#the-carpentries-lab) is for... 

Both of these sections of the page are linked again on the sidebar and in the sentence [More information about The Carpentries Incubator, The Carpentries Lab, and how this table is built is available at the end of this page](https://carp-new-website.netlify.app/lesson-development/community-lessons/#the-carpentries-incubator) - and I think that's sufficient. 

- [x] In this sentence: [More information about The Carpentries Incubator, The Carpentries Lab, and how this table is built is available at the end of this page](https://carp-new-website.netlify.app/lesson-development/community-lessons/#the-carpentries-incubator) - please revise to say instead "... and how the table below is..."

**Information for Lesson Developers**:
- [x] Please revise the last sentence to read: "... please contact the Incubator team at [incubator@carpentries.org](mailto:incubator@carpentries.org).
---

**Comment by maneesha** [comment]
The items that are checked off above are addressed with PR #240.

There are several items that are tagged for @tobyhodges to advise on so I am assigning this issue to Toby.

I am working on the issue with the image.

**Comment by tobyhodges** [comment]
> In the introductory paragraph, the link to [Carpentries Collaborative Lesson Development Training](https://carp-new-website.netlify.app/lesson-development/#about-the-training) links to the page that it's on... Was this meant to link to the curriculum? In that case, this: https://carpentries.github.io/lesson-development-training/ However, there is a link to the curriculum further down, so perhaps we just remove this hyperlink here completely. CC-ing @tobyhodges for input.

This is a hangover from when the CLDT info was part of a larger page. The link can be removed.

> Under "Target audience" I think we need to mention that ideally the training requires 2 or more people to register to collaborate together to develop the lesson, and also that at least one person in the lesson team must have attended The Carpentries Instructor Training. I know this is expanded on in the FAQ, but it also needs to be here as it is key information. CC-ing @tobyhodges for input.

Sure, I am happy for this to be changed. How about adding this to the end? "Trainees join the training in teams of 2-5 people, and at least one member of each team should have attended \[Instructor Training](link-to-instructor-training-info-page)."

> "Who teaches Collaborative Lesson Development Training?" - the mention to "a multi-week program of Trainer Training" needs to specify which Trainers we are referring to. Is it Lesson Developer Trainer Trainers or some other type of trainers? Cc-ing @tobyhodges to clarify.

Please change to "a multi-week program of Lesson Developer Trainer Training"

> "What options exist for a lesson after the training?" - the link to [consideration as a new lesson program](https://carp-new-website.netlify.app/lesson-development/cldt-faq/#) links to the page that it is on. I suspect it was meant to lead to this page in the Handbook: https://docs.carpentries.org/topic_folders/governance/lesson-program-policy.html#lesson-program-incubation-roadmap CC-ing @tobyhodges for input.

You are correct, please update the link but be aware that the URL will almost certainly change when the new handbook is launched.

**Comment by maneesha** [comment]
The image sizing has been adjusted and the feedback from Toby has been incorporated.
