### ISSUE TITLE
Website footer links

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/new-website#238]
---

- [x] The "[Get involved](https://carp-new-website.netlify.app/community/get-connected/)" footer is linking to the "Get connected" page. 
- [x] The [Request a workshop](https://carp-new-website.netlify.app/host/host-workshop/) footer has a broken link. 
- [x] The [Instructor Trainer Training](https://carp-new-website.netlify.app/trainer-training/) footer has a broken link.
- [x] Please change the link for the [Carpentries Incubator](https://carpentries-incubator.org/) footer to this link instead: https://carp-new-website.netlify.app/lesson-development/community-lessons/#the-carpentries-incubator
- [x] Please change the link for the [Carpentries Lab](https://carpentries-lab.org/) footer to this link instead: https://carp-new-website.netlify.app/lesson-development/community-lessons/#the-carpentries-lab
- [x] The link to our Slack channel (on the Slack icon in footer) does not seem to be working? 
- [ ] The link to the [Privacy Policy](https://carp-new-website.netlify.app/privacy/) is broken. 

---

**Comment by maneesha** [comment]
Everything except the privacy policy link is addressed with #239.
The privacy policy needs to be updated in the theme.  See [issue in that repo](https://github.com/carpentries/carpentries-hugo-theme/issues/55).

**Comment by froggleston** [comment]
Pirvacy link fixed in https://github.com/carpentries/new-website/pull/275 and https://github.com/carpentries/carpentries-hugo-theme/pull/56
