### ISSUE TITLE
Code of Conduct Committee

### ISSUE THREAD

**Issue by kariljordan** [carpentries/new-website#24]
The Carpentries Code of Conduct Committee

The Carpentries is dedicated to developing and empowering a diverse community of enthusiasts around computational methods for research and data science. To facilitate this, The Carpentries has established a [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html) that governs behavior within the community. The Code of Conduct committee was established to enforce the Code and to manage any changes and updates to it.

Our Goal:
To maintain, update, and enforce The Carpentries Code of Conduct (CoC).

Our Approach:
We do this by conducting meetings where we review current CoC issues. If a CoC violation is reported to us, we process that by following the Enforcement Manual.

Our Structure:
We have meetings as needed, and we have a private email list where Code of Conduct issues are discussed. We also have a private GitHub repo for internal discussion and organisation.

Our Leadership:
The structure of the committee is such that a community member is the Chair of the Committee. In addition, a Core Team liaison is part of the committee, and a member of the Board of Directors serves as a Board liaison.

Contacting the Committee:
Please email your concerns to [coc@carpentries.org](mailto:coc@carpentries.org). All correspondence will be treated in confidence.

Our Governance Structure: Please see the [Code of Conduct Committee (CoCc) Governance document](https://docs.carpentries.org/topic_folders/policies/coc-governance.html) to find details on membership, onboarding, administration, positions, roles, and responsibilities.
Current Committee Members
Chair

[D. Sarah Stamps](https://github.com/dsarahstamps) is an Associate Professor of Geophysics at Virginia Tech in the Department of Geosciences. She runs the Geodesy and Tectonophysics Laboratory, which is a research group that conducts research that entails measuring the Earth’s surface motions with millimeter precision and using computational modeling to understand the physical processes driving the Earth’s volcanoes, earthquakes, and continental deformation while training future leaders that are culturally effective. She is the current chair of the CoC committee.
CoC Liaisons

Core Team Liaison: [Kari L. Jordan](https://github.com/kariljordan) is the Executive Director at The Carpentries and serves as the [Core Team](https://carpentries.org/team/) liaison to the CoC Committee.

Board of Directors Liaison: [Jannetta Steyn](https://github.com/jsteyn) is a senior research software engineer at Newcastle university. She has been an instructor since 2020 and instructor trainer since 2021. She is also the convenor of the [CarpentriesOffline](https://carpentriesoffline.org/) development team. Jannetta is an elected member of the Board of Directors and serves as the liaison to the Code of Conduct committee.
Volunteer Members

[Andrea Sánchez-Tapia](https://github.com/AndreaSanchezTapia) is a biologist with a background in biodiversity informatics and a certified Carpentries Instructor since 2021. She has been part of Open Source communities of practice since 2017. She believes creating safe and inclusive spaces is necessary for the practice of open and responsible research.

[Annajiat Alim Rasel](https://github.com/annajiat) is a senior lecturer and program coordinator for undergraduate Computer Science and Engineering within the School of Data and Sciences, the largest school at Brac University, Bangladesh, under the umbrella of the world’s largest NGO, Brac. He is continuously learning from the students and colleagues. He is grateful for having co-taught courses on problem-solving, natural language interfaces and processing, data science, modeling and simulation, machine vision, parallel, distributed, and high-performance computing (HPC), ethical hacking, etc., along with interdisciplinary workshops and training events. The Carpentries community has been a source of immense growth for him. He is thankful to have had the opportunity to learn from everyone while serving the global community. He has served as an instructor, trainer, mentor, curriculum advisor, member of the executive council (EC, now transitioned into the board of directors), trainers leadership committee, code of conduct committee (CoCc), instructor development committee, steering committee for HPC carpentry curriculum development, organizing committee for CarpentryCon, etc. Having joined the CoCc in 2022 and then the EC, he had the opportunity to serve both groups as an EC liaison to the CoCc during 2022–2023. He returned as a CoCc member in 2024 to continue the commitment to fostering a safe and inclusive learning environment. Looking ahead, he is passionate about bridging the digital divide, particularly through ICT4D, with a focus on ICT4ED. He believes in the power of open educational resources, free/libre open-source software, tools, and good practices for research, development, engineering, and education. This includes promoting diversity, democracy, transparency, localization, accessibility, and other aspects of FAIR and CARE principles. Together, he dreams of ensuring a safer community of practice, empowering community members, and building a larger Carpentries community in Bangladesh, Asia, and worldwide.

[Karin Lagesen](https://github.com/karinlag) is a bioinformatician working at the Norwegian Veterinary Institute. Her time is spent building pipelines, teaching people how to analyze their data, and finding new and better ways of using bioinformatics for microbial surveillance. She was the chair of the CoC committee for 2 years, a member of the Software Carpentry Steering Committee for three years, and is also an instructor trainer. Karin is part of this committee because she believes it is very important to ensure that The Carpentries is safe and welcoming.

[Lora Leligdon](https://github.com/leligdon) is the Head of Research Data Services at Dartmouth Library, in Hanover, NH, USA. She is also a co-founder of the New England Software Carpentry Library Consortium ([NESCLiC](https://www.nesclic.com/)), an alliance of academic institutions in the northeastern US that joined the Carpentries together to create a community of practice to promote reproducible research and open science across our campuses.

[Malvika Sharan](https://github.com/malvikasharan) is a co-lead of The Turing Way project and a Senior Researcher at the Alan Turing Institute, UK. She co-founded and is a co-director of OLS (previously Open Life Science). She became a Trainer with The Carpentries in 2015 while carrying out her Ph.D. research in bioinformatics. She hosted and taught at multiple instructor training, software, and data workshops in Europe, and internationally. She co-chaired the first CarpentryCon that took place in Dublin in 2018. Her previous involvements in The Carpentries community include her participation in the mentoring program, instructor discussions, and CarpentryCon+Connect Taskforce. Her motivation for participating in The Carpentries CoC stems from her passion for promoting inclusiveness and accessibility in open research. She has been in the CoC committee since 2018 and chaired the committee between 2021-2023.

[Yo Yehudi](https://yo-yehudi.com/) is the Executive Director and co-founder of [Open Life Science](https://openlifesci.org/), a Software Sustainability Institute Fellow, NASA TOPS Training module lead, and EngD. student at the University of Manchester studying pathogen-related data sharing and sustainability of open-source software. Previous roles include an editor for the PLOS Open Source Toolkit, Code First Girls coding instructor, Mozilla volunteer, editor emeritus for the Journal of Open Source Software, board member of the Open Bioinformatics Foundation, and a software developer working on an open source biological data warehouse called InterMine, based at the University of Cambridge.

[Jean Baptiste Fankam Fankam](https://www.linkedin.com/in/jean-baptiste-fankam-fankam-19b728a2/) is a post-doctoral research fellow at the University of the Witwatersrand. After completing a PhD in Physics with a focus on Computational Materials Science in December 2021 at the University of Yaounde I, Cameroon, he sought to deepen his knowledge of CLI, Unix shell, and Python programming. Recognizing the importance of High-Performance Computing (HPC) for international recognition in his field, he searched for workshops and discovered a transformative online Carpentries Workshop on Unix shell. This led him to pursue further training, becoming a certified Carpentries instructor in April 2023 and later a Carpentries Maintainer. His active participation in the Carpentries community motivated him to apply for a leadership role on the Code of Conduct Committee. Since certification, he has taught numerous workshops locally and internationally, demonstrating his commitment by ensuring stable internet connections for his sessions, even while completing a postdoctoral position at the University of the Witwatersrand in South Africa. He will be available for a data science or AI-based position after August 2024.

Areas of responsibility:
1. Incident Response Leads: Facilitate report handling, identify chairs and Incident response group, and ensure the publication of transparency reports quarterly - D. Sarah Stamps and Lora Leligdon
2. Training Leads: as part of regular business meetings - scenario curation, training/reading material accumulation, CoC facilitators program - Karin Lagesen and Yo Yehudi
3. Onboarding and discussion Leads: Onboarding/offboarding and discussion on topics that come up in incident response or other interactions such as communication and cultural diversity situations: Andrea Sánchez Tapia and Malvika Sharan
-----------
@maneesha I'm having difficulty deciding what should be on the website vs. what should link out to the handbook. To me, areas of responsibility should be in the handbook.

**Comment by maneesha** [comment]
Edited Kari's comment above for formatting.

**Comment by maneesha** [comment]
In response to question above about where areas of responsibility go -- as it is just the three items, I think it is fine here.  If we included detailed guides on how to do things, that would go in the Handbook.
