### ISSUE TITLE
Style changes to "Curriculum Summary" page 

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/new-website#242]
---
**Curriculum Summary**: https://carp-new-website.netlify.app/lessons/curriculum-summary/#software-carpentry-all-workshops

- [x] Please rename this section from "Curriculum Summary" to "Curriculum Overview"
- [x] All the links to [This workshop] at the beginning of every curriculum summary lead to the old lesson program sites, and not the new ones. 
- [x] Under "Data Carpentry: Geospatial" please spell "specialized" as "specialised".
- [x] Under "Software Carpentry (All Workshops)", the link to SWC leads to the old lesson program site. 
- [x] For all the SWC workshop headings, please remove the (barckets) and use the : instead, for uniformity with the other workshop lesson headings. 
- [x] Under "Community Developed Lessons" - the link to our [Community Developed Lessons page](https://carp-new-website.netlify.app/community-lessons/) is broken. 

---

**Comment by maneesha** [comment]
* The page title is already currently "Curricula Overview"
* Anchor links have been fixed. The base url should remain for when we launch the new sites.
* British spelling fixed
* SWC lessons styled with colon instead of parentheses
* Link to community lessons fixed
