### ISSUE TITLE
Spanish lessons do not show up when filtering by tool

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/new-website#267]
I don't think this is exactly critical, but it is incorrect, so raising an issue for awareness. The filtering tool on the lessons page doesn't show all language matches when filtering for a specific tool. Example shown below: 

When filtering for "Git" only English language lessons appear. 

<img width="1276" alt="Screenshot 2024-11-01 at 9 43 30 AM" src="https://github.com/user-attachments/assets/3bcbf9b1-b885-4165-b5ba-ae4960ea6038">

Filtering for "Git" and "Spanish" language shows no results.

<img width="1279" alt="Screenshot 2024-11-01 at 9 43 38 AM" src="https://github.com/user-attachments/assets/305df52a-bc2d-48cd-8c74-91a0ca691e7f">

When filtering for "Spanish" only, the Git lesson in Spanish appears. 

<img width="1272" alt="Screenshot 2024-11-01 at 9 43 20 AM" src="https://github.com/user-attachments/assets/44a4741a-91e5-4778-babf-9b8e503df704">

This also seems to be the case for the R lessons, so I'm guessing that there's an error in the filter logic.

**Comment by maneesha** [comment]
@ErinBecker This has been fixed.  This was due to the source data on Spanish language having some incomplete fields.
Can you test it out and see if it works as expected? Close this issue if it works; otherwise please share any other feedback here.

**Comment by maneesha** [comment]
Assigning to @ErinBecker for review.
