### ISSUE TITLE
Pricing page

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/new-website#46]
https://carp-new-website.netlify.app/host/pricing/

In "Overview" section, please add link
[World Bank’s gross national income categorisation](https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups)

Membership Pricing table should include current membership prices from https://carpentries.org/membership/. Zeros should be populated. Final row of table should be "Low Income" to match other tables. 

For section with header  "Membership Pricing", change text to 

"Memberships include a bundle of Workshops and Instructor Training seats for organisations seeking to provide computational and data training to their community. Members can add-on additional Workshops and Instructor Training seats to their Membership package at a 40% discount to the prices shown above. For more information about Membership, visit our [Membership page](https://carp-new-website.netlify.app/support/membership/).

**Comment by maneesha** [comment]
@ErinBecker please review the page here: https://carp-new-website.netlify.app/host/pricing/

If all looks good, you can close this issue.  If you see any other changes needed, please note them here.

**Comment by ErinBecker** [comment]
@tobyhodges - we need a few sentences under the Collaborative Lesson Development Training header. Could you please suggest text? 

"Contact us" section says "please send us an email to". Change to either "please send an email to" or "please send us an email at". 

Please place zeros in the Membership table where none of the benefit type is included in the package. 

No other changes!

**Comment by maneesha** [comment]
Re-assigning to @tobyhodges to provide language about CLDT and to me to implement all changes.

**Comment by tobyhodges** [comment]
Suggested wording for CLDT:

Collaborative Lesson Development Training gives your community members the skills they need to design and implement effective, accessible curriculum together. Our two-part, 24-hour training teaches best practices in curriculum design and collaborative development of an open source lesson website.

**Comment by maneesha** [comment]
@tobyhodges  did you get to discuss this at the Management Team meeting?

**Comment by tobyhodges** [comment]
I'm afraid we did not have time in recent meetings. I will ask on the team Slack channel...

**Comment by tobyhodges** [comment]
Please adjust wording above the membership pricing table:

> Members can add-on additional Workshops, Instructor Training seats, and Collaborative Lesson Development Training to their Membership package at a 40% discount to the prices shown above.

**Comment by maneesha** [comment]
@tobyhodges Your note above has been addressed. 
Please share here when you have more language for the CLDT section.

**Comment by maneesha** [comment]
Removing myself as assignee for now.  I will make the changes once @tobyhodges  has shared the CLDT language.

**Comment by tobyhodges** [comment]
CLDT language was provided in [a previous comment up-thread](https://github.com/carpentries/new-website/issues/46#issuecomment-2361473296)

**Comment by tobyhodges** [comment]
> Members can add-on additional Workshops, Instructor Training seats, and Collaborative Lesson Development Training to their Membership package at a 40% discount to the prices shown above.

I just noticed that the equivalent change should also be made on one of the bullet points on https://carp-new-website.netlify.app/support/membership/

**Comment by maneesha** [comment]
> CLDT language was provided in [a previous comment up-thread](https://github.com/carpentries/new-website/issues/46#issuecomment-2361473296)

@tobyhodges You provided language above but then also noted to leave this open for now as it was being discussed.  Have you confirmed the above language is good?

**Comment by maneesha** [comment]
> > Members can add-on additional Workshops, Instructor Training seats, and Collaborative Lesson Development Training to their Membership package at a 40% discount to the prices shown above.
> 
> I just noticed that the equivalent change should also be made on one of the bullet points on https://carp-new-website.netlify.app/support/membership/

@tobyhodges Can you share what you are referring to here?  We want to keep anything related to pricing all on only one page to keep consistency if we need to make pricing changes.

**Comment by tobyhodges** [comment]
> You provided language above but then also noted to leave this open for now as it was being discussed. Have you confirmed the above language is good?

Yes, please use the language provided above.

> Can you share what you are referring to here?

On , we currently say:

> In addition to the benefits above, all Memberships include:
>
> * quarterly reports on benefit usage and trainee progress towards certification,
> * opportunity to submit a candidate for our Trainer Training course, through which individuals can become certified to teach our Instructor Training courses (additional fees apply),
> * unlimited self-organised workshops,
> * access to Member pricing for additional Centrally-Organised workshops and Instructor Training seats purchased during the membership year.

I suggest updating the last bullet in that list to say "access to Member pricing for additional Centrally-Organised workshops, Instructor Training, and Collaborative Lesson Development Training seats purchased during the membership year."
