### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/new-website#47]
https://carp-new-website.netlify.app/support/membership/

Change first heading to "Become a Member". Remaining text in that paragraph is good. 

In "Why Membership?" section

- Is there an extra empty line between the header and the first table item? It looks oddly padded. 
- Bold the first sentence in each table item and separate with a hyphen instead of a period, for example:

**Hands-on, practice-based training in teaching** - receive priority access to our Instructor Training program, which will empower high-quality instruction at your institution and certify leaders in your community to teach Carpentries workshops.

- The checkmark icons next to each table item are really small on my browser and hard to read as checkmarks.

In the "Membership Levels" section: 

- include link to World Bank income levels like on the [Pricing page](https://github.com/carpentries/new-website/issues/46). 
- Include disclaimer about for-profit pricing like on the [Pricing page](https://github.com/carpentries/new-website/issues/46). 
- Add the paragraph and bullet points starting "In addition to the benefits above, all Memberships include:" from [the current Membership page](https://carpentries.org/membership/). On the current Membership page, this is located right above the "Become a Member Organisation" button. 

Bronze Membership
Appropriate for organisations that want to experience The Carpentries teaching model, but do not yet have organisational interest in building up a local Instructor pool.

Silver Membership
Our most popular level! Appropriate for organisations that are ready to start building their local Instructor community, but still want some support on workshop administration. 

Gold Membership
Best for organisations that are ready to scale up their local workshop offerings and start becoming independent of The Carpentries' administrative support. 

Platinum Membership
Ideal for organisations that run a lot of Self-Organised workshops and want to keep growing their local Instructor pool.

Titanium Membership
An option for organisations that want to continue supporting The Carpentries financially, but don't need support with workshop organisation or Instructor Training. 

Remove the section on Financial Support.

In the "Questions" section: 
- Have questions about the membership program? Please consult our Membership FAQ (LINK) or contact the [Membership Team](mailto:membership@carpentries.org).

**Comment by ErinBecker** [comment]
@elletjies - just a heads up about this issue. If you have any changes you'd like to suggest, please feel free!

**Comment by maneesha** [comment]
@ErinBecker  For the question about the empty line above the first item that looks oddly padded as well as the small check marks, this is because we were coercing this view into one of the styles we have available.  Instead, we could have this be a simple bulleted list.  What do you think?

**Comment by maneesha** [comment]
@ErinBecker please review the page here: https://carp-new-website.netlify.app/support/membership/ 

If all looks good, you can close this issue. If you see any other changes needed, please note them here.

**Comment by ErinBecker** [comment]
The "Become a Member" button looks like it belongs to the Titanium Membership section rather than to the page as a whole. Suggestions on how to make it appear separate: 
- increase spacing between end of Titanium section and button
- center button
- make button larger

I'll leave it to @OscarSiba to advise on which of these options (or another option) is most appropriate visually. 

No other changes!

**Comment by maneesha** [comment]
Thanks @ErinBecker 

Reassigning to @OscarSiba to advise about the button and to me to implement changes to button and the bulleted list.

@OscarSiba For the changes to the button, I would recommend either center or increasing space as changing size will be more difficult to implement.

**Comment by ErinBecker** [comment]
@maneesha  - while reviewing other website pages I've noticed that the table formatting is used in other places. I'm ok with leaving it as is on this page to match the formatting across the page. Please remove that to-do item from the list.

**Comment by maneesha** [comment]
Removing myself as an assignee for now.  I'll make the changes once @OscarSiba  has made recommendations here.

**Comment by maneesha** [comment]
@OscarSiba  Can you review the page with the moved button? If it looks good, please close this issue. Otherwise you can leave more feedback here.
