### ISSUE TITLE
Get involved

### ISSUE THREAD

**Issue by elletjies** [carpentries/new-website#50]
Remove the verbiage currently on the page and add the following: 

The Carpentries works to help institutions and individuals spread skills for data analysis, computational thinking, and research software development through building local and global communities of practice.

Our work is made possible by our amazing volunteer Instructors, Trainers, Mentors, Maintainers, curriculum advisors, helpers, workshop hosts, organisers and member organisations.

**Header**: You can get involved in: (this comes from https://carpentries.org/community/) Note: I am also not sure where these pages will live now or if they still exist, I can clean them up during the next round if this will help. 

* Overseeing the training and certification of [Instructors](#instructors)
* Maintaining global communities of practice:
	* [Governance](#governance) - community members that constitute the governance and policy arm of The Carpentries
	* [Trainers](#trainers) - those who prepare our new Instructors
	* [Lesson developers](#lesson-developers) - those who create new lessons
	* [Curriculum advisors](#curriculum-advisors) - those who guide development of existing lessons
	* [Lesson maintainers](#maintainers) - those who support existing lessons
	* [Regional Coordinators](#regional-coordinators) - those who coordinate workshops regionally
	* [Code of Conduct Committee](#code-of-conduct-committee) - those who keep our community friendly and welcoming

* Keeping our community strong and connected through meetups (virtual and in-person) and interest-specific mailing lists
	*	[CarpentryCon](#carpentrycon) - our annual in-person meetup for our global community
	*	[CarpentryConnects](#carpentryconnects) - regional community conferences organised by regional coordinators and local community members in The Carpentries
	*	[Community sessions](#community-events)
	*	[Mailing lists](https://carpentries.topicbox.com/latest)

* Here are some currently inactive roles that community members have fulfilled in the past:
	* [Mentors](#mentoring-groups) - those who provide support to other instructors
	* [Instructor development](#instructor-development) - those who support Instructors as they build their skills
	* [Champions](#champions) - those who work to spread our impact locally
	* [Assessment Committee](#assessment-network) - those who help us understand our impact
	* [Lesson infrastructure Committee](#lesson-infrastructure) - those who support lesson building and styling

### Governance

The Carpentries is a fiscally sponsored project of [Community Initiatives](https://communityinitiatives.org/), a registered 501(c)(3) non-profit based in California, USA. The Carpentries is [transitioning out of fiscal sponsorship](files/pdf/Fiscal_Sponsorship_Transition_FAQ.pdf) to an independent 501(c)(3) non-profit organisation. For that reason, the organisation has two governing bodies: an Advisory Committee and a Board of Directors.

More information about our governance and current members is available on [the Governance page](/governance/).

### Instructors
The Carpentries Instructors are the core of our community. Instructors organise and teach Carpentries workshops to spread data literacy and programmatic skills both locally and globally. Members of our Instructor community work together to actively grow their instructional and technical skills. Becoming an Instructor is a great step to leveling-up your own technical skills and helps you to become a more effective technical communicator.

* [Instructor training curriculum](https://carpentries.github.io/instructor-training/)
* [Become an Instructor!](/become-instructor/)
* [Update]({{site.amy_landing}}) your instructor profile
* For more information, contact us at [{{site.instructor_training_contact}}](mailto:{{site.instructor_training_contact}}).

### Instructor Development

Instructor development is how our global instructors come together to support each other and develop new teaching and
technical skills. We create an open and inviting environment through community sessions and project-based small group mentoring.

#### Instructor Development Committee

The Instructor Development Committee supports Instructors as they progress through training, teaching, curriculum development, and other community-related activities. They help promote community-building and networking, by providing virtual spaces where instructors from all over the world can share teaching success stories and discuss teaching strategies.

* [Training materials]({{site.handbook_url}}/topic_folders/instructor_development/instructor_development_committee.html)
* [Instructor Development Committee roles]({{site.handbook_url}}/topic_folders/instructor_development/instructor_development_committee.html#instructor-development-committee-roles)
* Join: Join the Instructor Development Committee by attending our monthly meeting.
* [Upcoming meetings](http://pad.carpentries.org/instructor-development)
* [Mailing list]({{site.mailing_lists}}/instructor-development)
* For more information, contact [Sher! Hurt](mailto:sheraaron@carpentries.org).

### Trainers
The Trainer community is a group of experienced Instructors, local champions, and education specialists who inspire and prepare new Instructors. They work as a team to maintain and teach the [instructor training curriculum](https://carpentries.github.io/instructor-training/). They also host teaching demonstration sessions to provide vital feedback as prospective Carpentries Instructors prepare to join the community. They showcase and embody the enthusiasm and conduct of our community as they prepare new instructors. Becoming a Trainer lets you scale your impact - sharing your own passion, experience, and enthusiasm with the next generation of The Carpentries Instructors.

* [Trainer Training materials](https://carpentries.github.io/trainer-training/)
* [Duties]({{site.handbook_url}}/topic_folders/instructor_training/duties_agreement.html#trainer-agreement)
* [Current members](https://github.com/carpentries/trainers/blob/main/README.md#current-members)
* [Meeting minutes](https://github.com/carpentries/trainers/tree/main/minutes)
* [Contact](mailto:{{site.instructor_training_contact}})

Private resources for current Trainers:
* [Upcoming meetings](http://pad.carpentries.org/trainers) *Meetings are private to Trainers and invited guests*
* [Mailing list]({{site.mailing_lists}}/trainers) *This list is private to Trainers*
* [Slack]({{site.slack_invite}}) *This Slack channel is private to Trainers*

### Maintainers
The Carpentries Maintainers work with the community to make sure that lessons stay up-to-date, accurate, functional and cohesive. Maintainers monitor their lesson repository, make sure that pull requests and issues are addressed in a timely manner, and participate in the lesson development cycle including lesson releases. They endeavor to be welcoming and supportive of contributions from all members of the community. This community of practice is a great place to learn to collaborate effectively in Git and GitHub. Upcoming rounds of Maintainer Onboarding will be announced on our [newsletter]({{ site.url }}{{ site.baseurl }}/newsletter/) and [blog]({{ site.url }}{{ site.baseurl }}/blog/).

* [Training materials](https://carpentries.github.io/maintainer-onboarding/)
* [Maintainer guidelines]({{site.handbook_url}}/topic_folders/maintainers/maintainers.html#maintainer-guidelines)
* [Upcoming meetings](https://codimd.carpentries.org/maintainers?both)
* [Mailing list]({{site.mailing_lists}}/maintainers)
* [Slack]({{site.slack_invite}})
* [Contact](mailto:curriculum@carpentries.org)

### Curriculum Advisors
Curriculum Advisors provide high-level guidance on the overall structure of a particular curriculum,
including which tools will be taught and which dataset(s) will be used for the lessons.
They bring domain-specific expertise to lesson development and help ensure that
lessons stay up to date with advances in technology. Being a Curriculum Advisor is a great way to keep up-to-date about changes in your field and
network with other domain experts in The Carpentries community. We are not currently seeking new members to the Curriculum Advisory Committees.

* [Curriculum Advisory Committee Members]({% link pages/curriculum-advisors.html %})
* [Curriculum Advisory Committee (CAC) Duties]({{site.handbook_url}}/topic_folders/lesson_development/curriculum_advisory_committees.html#roles-and-responsibilities)

### Lesson Developers

The Carpentries community is committed to a collaborative and open process for lesson development and to sharing teaching materials. We provide two avenues for community members to share lesson materials.

[The Carpentries Incubator](https://carpentries-incubator.org/) is for Carpentries community members to share Carpentries-style teaching materials at all stages of development, to receive feedback from other community members. These lessons are not officially endorsed by The Carpentries. Read [more information](https://github.com/carpentries-incubator/proposals/blob/master/README.md) about contributing to The Carpentries Incubator.

[The Carpentries Lab](https://carpentries-lab.org/) is for sharing peer-reviewed lessons, vetted by The Carpentries. We are currently piloting [an open peer review process for lessons entering The Carpentries Lab](https://github.com/carpentries-lab/reviews/). Although the system is open for submissions, we can currently only commit to review those lessons that have been invited. If you would like to volunteer as a reviewer for The Carpentries Lab, please send an email to [incubator@carpentries.org](mailto:incubator@carpentries.org).

Those looking for ways to contribute to existing lesson material can find
a list of issues in need of attention on the [Help Wanted page](/help-wanted-issues/).

### Regional Coordinators

Regional Coordinators are the front face of The Carpentries, promoting our work and our culture in their geographical area. They manage workshop logistics, communicate with hosts and Instructors, and respond to general inquiries. They work together to support each other and ensure communities can thrive locally while maintaining quality and consistency globally.

* [Regional Coordinators]({% link pages/regional_coordinators.html %})
* [Duties]({{site.handbook_url}}/topic_folders/workshop_administration/expectations.html)
* [Contact](mailto:{{site.contact}})

### Code of Conduct Committee

The Carpentries is a community-led project. We are committed to creating a friendly and respectful place for learning, teaching and contributing. The Code of Conduct Subcommittee handles reported code of conduct violations and works to keep our community welcoming for all.

* [The Carpentries Code of Conduct]({{site.handbook_url}}/topic_folders/policies/index_coc.html)
* [The Code of Conduct Committee](/coc-ctte/)
* [Apply to join](https://goo.gl/forms/9NMhirB5wXGZ2FUc2)
* Upcoming meetings: Meetings are closed to the group for confidentiality reasons.
* Mailing list: This mailing list is confidential.
* For more information contact [Karin Lagesen](mailto:karin.lagesen@gmail.com).

### Spanish Translators Team

The Spanish Translators Team translates and maintains Spanish-language lessons for The Carpentries lesson programs. They are a part of The Carpentries en Latinoamérica group.

* To join, sign up for our [mailing list](https://groups.google.com/forum/#!forum/carpentries-traductores).
* Upcoming meetings - information coming soon!
* [Meeting minutes](https://github.com/carpentries/latinoamerica/tree/master/traducciones/minutos)
* For more information contact [The Carpentries](mailto:{{site.contact}})

### Regional Subcommunities

For a full listing of Carpentries subcommunities, please visit our [subcommunity registry](https://carpentries.org/community-groups/).

### CarpentryCon

The Carpentries hosts [CarpentryCon](http://www.carpentrycon.org/), a community-organised meeting for our global community.
* [CarpentryCon 2018](https://2018.carpentrycon.org/) was held from 30 May to 1 June 2018 in Dublin, Ireland.
* [CarpentryCon 2020](https://2020.carpentrycon.org) was held between July and August 2020 as a seven week online event.
* [CarpentryCon 2022](https://2022.carpentrycon.org/) will be 1-12 August 2022 as an online event.

If you are interested in helping to organise the next CarpentryCon, contact [The Carpentries](mailto:{{site.carpentrycon_contact}}).

### CarpentryConnects

CarpentryConnects are community convenings, organised to bring together community members of The Carpentries that are in close proximity geographically for knowledge exchange, collaboration, and networking. [The CarpentryConnect Planning Kit](https://carpentryconnect.org) provides checklists, templates, recommendations for best practices and resources to serve as guides in planning and carrying out CarpentryConnect events.

Here is a list of all CarpentryConnect events held in the past: [carpentryconnect.org/case-studies/](https://carpentryconnect.org/case-studies/)

### Champions

<mark>Carpentry Champions are an inactive subcommunity in The Carpentries</mark>. Champions used to meet quarterly to discuss ways in which they can help support the growth of existing communities and attract new communities to building digital skills capacity at research organisations around the world. Come and learn from senior community leaders and get support as you work to build your own local community. Here are resources with information about this inactive group:

* [Activities](https://github.com/carpentries/champions/blob/master/activities.md) - This community holds quarterly meetings.
* [Mailing list](https://carpentries.topicbox.com/groups/champions)
* [Meeting minutes](https://github.com/carpentries/champions/tree/master/meeting-minutes)
* [Carpentries Community Cookbook](https://cookbook.carpentries.org/)
* To get involved, contact our [Team](mailto:{{site.contact}}).

### Assessment Network

<mark>The Assessment Network is an inactive subcommunity in The Carpentries</mark>. It used to bring together those working on assessment within the open source/research computing space to collaborate and share resources. The network meets quarterly to discuss best practices and share resources.Here are resources with information about this inactive group:

* [Activities](https://docs.carpentries.org/topic_folders/assessment/assessment-network.html#about)
* [Current members](https://github.com/carpentries/assessment/blob/master/assessment-network/README.md#members)
* [Upcoming meetings](http://pad.carpentries.org/assessment-network)
* [Meeting minutes](https://github.com/carpentries/assessment/tree/master/assessment-network/minutes)
* [Contact](mailto:kariljordan@carpentries.org)

### Lesson Infrastructure

<mark>This is an inactive subcommunity in The Carpentries</mark>. Members of the Lesson Infrastructure Committee used to serve as Maintainers for [The Carpentries lesson template](https://github.com/swcarpentry/styles) and [its documentation](https://github.com/swcarpentry/lesson-example), as well as for [The Carpentries workshop template](https://github.com/swcarpentry/workshop-template).

* [Past members](https://github.com/carpentries/lesson-infrastructure#members)
* [Meetings](http://pad.carpentries.org/infrastructure-subcommittee)
* [Contact](mailto:curriculum@carpentries.org)

#### Mentoring Groups

<mark>This is an inactive subcommunity in The Carpentries</mark>. Mentoring Groups support Instructors in a variety of ways. Whether you are a new instructor preparing to teach your first workshop, a seasoned Instructor hoping to launch workshops in a new community, or an Instructor excited about getting involved with lesson development and maintenance, mentoring groups will help you gain the confidence, technical skills, and teaching skills you need to reach your goal.

* [Training materials]({{site.handbook_url}}/topic_folders/instructor_development/mentoring_groups.html)
* [Duties]({{site.handbook_url}}/topic_folders/instructor_development/mentoring_groups.html#mentor-agreement)
* [Join the #mentoring Slack channel]({{site.slack_invite}})
* For more information, contact [Alycia Crall](mailto:alycia@carpentries.org).

<hr>

### Community events
There are many opportunities to join community meetings, subcommittees and debriefing sessions. Find links to them in the Google calendar (link to Community events) to watch all that is going on throughout our community.

**Comment by maneesha** [comment]
@elletjies For now I am going to put this entire content in the "Get Involved" page.  I do think it needs a lot of work as there is a lot of outdated information.  For this reason, I have intentionally not updated any links.  Can you leave more information here as you review it about the changes you would like to see?

**Comment by elletjies** [comment]
@maneesha I agree the content needs a good review - I will do that during our next round of co-working sessions

**Comment by elletjies** [comment]
@maneesha I made updates in this PR - https://github.com/carpentries/new-website/pull/115

**Comment by maneesha** [comment]
@elletjies As we have merged #115 is there anything else you want to do with this page for now?  If not, you can close this issue.

**Comment by elletjies** [comment]
@maneesha for now we are good. Lets close the issue.
