### ISSUE TITLE
Banner image on front page 

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#65]
What banner image should we use on the front page? 
@OscarSiba has noted he likes what we have but we do not have appropriate credit to use it.

**Comment by OscarSiba** [comment]
As confirmed by @ErinBecker we already paid for use of this image, so we do not need to credit it. Erin, do you know if we kept proof of purchase somewhere?

**Comment by maneesha** [comment]
@OscarSiba Can you manage image rights separate from this website repo?  Closing this here as I don't think we need to do anything else.
