### ISSUE TITLE
What information should go in the bubble stats? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#66]
@OscarSiba  has recommended using the following stats. Opening this issue to ask the following questions: 

- Instructors - Active Instructors or all Instructors?
- Instructor Trainers - Active Trainers or all Trainers?
- Member Organisations - Current members or all time unique member orgs? 
- Countries - Countries of what? Member orgs? Workshops? Community members?

**Comment by OscarSiba** [comment]
Please use the following information: 

Instructors - all Instructors
Instructor Trainers - all Trainers
Member Organisations - all time unique member orgs
Countries - countries in which we've had workshops.

**Comment by maneesha** [comment]
Also, should we change the heading text from _"Our diverse and global community is comprised of"_?  The numbers do not represent our current community but rather all time data.

**Comment by OscarSiba** [comment]
Please use the precise numbers if easier to manage. Revise the "Our diverse and global community is comprised of" sentence to read: "Our diverse and global community has developed to".

**Comment by maneesha** [comment]
@OscarSiba for all time unique member orgs, would you like to see this regardless of dates/membership level? I feel this comes out to a grossly misleading number (268) as it includes a la carte memberships, historical level memberships, etc.

**Comment by maneesha** [comment]
This can be set up once our [new feed](https://github.com/carpentries/feeds.carpentries.org/pull/89) is merged.

**Comment by maneesha** [comment]
I like that wording better too.

**Comment by OscarSiba** [comment]
Agree with that wording suggestion from Rob!

**Comment by maneesha** [comment]
@OscarSiba  I did not hear back from you about my comment above (about number of members) so I included Instructors, Trainers, workshops, and countries instead. 

Please review how the bubble stats appear on the front page.  If it looks good to you, you can close this issue. Otherwise please share any other feedback here.

**Comment by maneesha** [comment]
@OscarSiba I did not hear back from you about my comment above (about number of members) so I included Instructors, Trainers, workshops, and countries instead.
