### ISSUE TITLE
Consistent length for testimonials

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#73]
We have two testimonials and the vary greatly in length.  Consider editing them to be similar in length (I'd go more like the shorter one) for a more consistent user experience.

**Comment by OscarSiba** [comment]
For the testimonials:

1. Please shorten Damien's to simply read: “I’m pretty sure I wouldn’t be a gainfully employed climate scientist without The Carpentries." 
2. For Saranya Canchi's testimonial, please update her designation to "Computational Lead, University of Michigan"
3. Please add this testimonial from Scott C. Peterson, "The Carpentries opened me up to learn things I had no idea I wanted to learn or could learn. It introduced me to a great community that made this possible." His designation should read, "Head of the Morrison Library & Graduate Services Library, University of California, Berkeley"

Scott's photo is in this images folder as scott_peterson-500x500.jpg.

**Comment by maneesha** [comment]
@OscarSiba  This has been changed. Please review. If it looks good, you can close this issue. Otherwise you can note any other changes here.

**Comment by OscarSiba** [comment]
In Saranya's testimonial please put a full stop at the end of her testimonial, just before the heart emoji. Then you can close this issue.

**Comment by maneesha** [comment]
Fixed with #174
