### ISSUE TITLE
Review lesson development section 

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#76]
Review [lesson development section](https://carp-new-website.netlify.app/lesson-development/).

I have taken the content from @tobyhodges's Google doc to set up the lesson development section of our website.  To be consistent with the structure of other sections, I have made the following changes: 

* Moved pricing table to the [pricing page](https://carp-new-website.netlify.app/host/pricing/). We are not keeping pricing information on any individual program pages as it becomes difficult to maintain when our fees change.
* Move FAQ to its own page (as we have for workshops, membership, etc.)  

Still to do:

- [ ] Add images (hex sticker & structure chart) 
- [ ] Add links to Handbook (will do that once everything is done) 

(edit to use general preview links, not PR previews)

**Comment by tobyhodges** [comment]
Thoughts from review 2024-09-19.

- Can we replace the "About the training" heading with "Collaborative Lesson Development Training" and remove the equivalent heading at the top of the page content? To me, it would feel better to have the three paragraphs of general blurb, about collaborative lesson development in the community, immediately underneath the page header i.e. without the second-level heading above it.
- There is a space missing after the comma in "[...] and want to begin developing it into an open source lesson website,in collaboration with others."
- (Note to myself) Based on the content of our [promotional pitch deck](https://docs.google.com/presentation/d/1fiSA_9jZTwEd40OsQ-ZfWpjgI9bTt6jqWgWj4u8FSRQ/edit#slide=id.g2edd406a36f_0_38) for the training, I think I might like to add a new section into this page about how CLDT and Instructor Training complement one another.

Excited to see how it looks with the images included! 🙌

**Comment by maneesha** [comment]
Assigning back to me to make fixes noted above and add images back in.

**Comment by maneesha** [comment]
- I have moved the heading as noted above.
- I do not see a missing space in the section noted above: 
![image](https://github.com/user-attachments/assets/7da28c8b-b87c-4cb3-bf7e-15f1e05bb8c4)

- I am still working on the images.  They are getting formatted weirdly.

**Comment by maneesha** [comment]
@tobyhodges I have updated the page with images.  Please see: https://carp-new-website.netlify.app/lesson-development/
