### ISSUE TITLE
Review Curriculum Advisors page 

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#78]
We have Curriculum Advisors pages set up on the individual lesson program sites.  @tobyhodges  please review the page on The Carpentries site and let me know what you think.

https://carp-new-website.netlify.app/community/curriculum_advisors/

**Comment by tobyhodges** [comment]
Notes from review on 2024-09-19:

- heading "How to list Curriculum Advisors?" should be removed
- "lesson program Governors" -> "Lesson Program Governors"

Otherwise all looks good, thanks! 🙌

**Comment by maneesha** [comment]
Re-assigning to me to make fixes noted above.
