### ISSUE TITLE
Review Maintainers/Alumni pages

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#81]
Review Maintainers/Alumni pages: https://carp-new-website.netlify.app/community/maintainers/

@tobyhodges I used the language you provided for the Maintainers and adjusted to make it work for alumni.  Let me know if you want to see different language there.  

I also like your suggestion about moving the "Why isn't my profile here" to a FAQ.  I've opened issue #79 to consider that.

**Comment by tobyhodges** [comment]
Notes from review on 2024-09-19:

Looks great, except that I would move the sentence "You can learn more about the Maintainer role, and how to become a Maintainer in our Maintainer Handbook." before the description of the page ("This page lists our current Maintainers"/"This page lists our past Maintainers.") So maybe:

> Maintainers are responsible for the day-to-day upkeep of our lessons - making sure they stay accurate, up-to-date, functional, and cohesive. You can learn more about the Maintainer role, and how to become a Maintainer in our Maintainer Handbook.
> 
> This page lists our current Maintainers. Previous Maintainers are listed on our [Maintainer Alumni](https://carp-new-website.netlify.app/community/maintainer-alumni) page.

**Comment by maneesha** [comment]
Assigning back to me to make fixes noted above.

**Comment by maneesha** [comment]
@tobyhodges This has been fixed. If this looks good to you, please close this issue.  Otherwise you can raise any other questions you have here.

**Comment by tobyhodges** [comment]
Looks great, thanks @maneesha
