### ISSUE TITLE
Intro text on past/upcoming workshops

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#83]
For review by @danielle06.  Intro text has been added to past & upcoming workshops pages.

* https://carp-new-website.netlify.app/workshops/upcoming-workshops/
* https://carp-new-website.netlify.app/workshops/past-workshops/

Edit to add your note about adding a reminder to clear the search is being addressed in this issue: https://github.com/carpentries/carpentries-hugo-theme/issues/46

**Comment by danielle06** [comment]
This looks great!

**Comment by danielle06** [comment]
Thanks, Maneesha. This looks great!
