### ISSUE TITLE
Review workshops main page & host page

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#88]
We have two pages that provide general introductory language about our workshops: 

* [Host a workshop](https://carp-new-website.netlify.app/host/host-workshop/)
* [Workshops (main page)](https://carp-new-website.netlify.app/workshops/)

These pages also link to the [curriculum overview page](https://carp-new-website.netlify.app/lessons/curriculum-summary/).

It seems like there is repetitive information in the two pages.  We would benefit from reviewing the pages together (and perhaps with the workshops FAQ, in an upcoming PR) so our language is more focused.

**Comment by maneesha** [comment]
@sheraaronhurt @danielle06  As we talked about today, here is a preview of what the site would look like if there was no "Host" at the top menu, and if we added "Host" to the workshops tabbed menu.

https://deploy-preview-107--carp-new-website.netlify.app/

**Comment by sheraaronhurt** [comment]
@danielle06 and I reviewed and agree there is overlap. Danielle will update the pages. 

We also do like the updated option with the "Host" in the Main Workshop view.

**Comment by maneesha** [comment]
@sheraaronhurt @danielle06 I have made the changes, adding the "host" section to the workshops section.  Please review.  If it all looks good, please say so here and close this issue.
Otherwise, you can share any other feedback you have.
