### ISSUE TITLE
Order of items in "Learn" menu 

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#89]
The "Learn" menu has the following items in this order:

* Lessons
* Workshops
* Instructor Training
* Trainer Training
* Lesson Development

What order should these items be in? The order is currently arbitrary.  Item order can lead to interpretations of hierarchy, so I'd recommend having an intentional order or have things in alphabetical order.

**Comment by maneesha** [comment]
@OscarSiba Please look at how the "Learn" menu is now.  If it looks good to you, please say so here and close this issue. Otherwise you can leave a note about other changes we should make.

**Comment by OscarSiba** [comment]
I am happy with this, thanks Maneesha.
