### ISSUE TITLE
Should "Alumni" pages for community roles be on the same page as main role? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#90]
Currently, for the roles of Trainer and Maintainer we have a page for people in active roles and an Alumni page.  We would plan to do the same thing for Instructors (once we plan the active status project for them).  @sheraaronhurt  has [suggested having Alumni on the same page](https://docs.google.com/document/d/1GVHb7NHOZmU6S0Ik5kz_aqi0HFuioQirDzAiMZUf9U8/edit?disco=AAABU3ZDdrc). 

Opening this issue for discussion to see what people think of this. I think this could make the pages get very long but we can have a ToC to ease navigation.

**Comment by maneesha** [comment]
Preview what it would look like to have Alumni on the same page:

* [Instructor Trainers](https://deploy-preview-94--carp-new-website.netlify.app/community/instructor-trainers/)
* [Maintainers](https://deploy-preview-94--carp-new-website.netlify.app/community/maintainers/)

**Comment by maneesha** [comment]
Assigning to @sheraaronhurt  and @tobyhodges as they work with the communities where we list people like this and to @OscarSiba for general feedback.

**Comment by tobyhodges** [comment]
I quite like the single page view: I think the navigation on the right is sufficiently prominent that the alumni do not get lost down the page. My only concern is about whether people might search the page for a specific person's name, find them but not realise they are in the list of alumni, and mistakenly think they are still active in the role. Typing it out, that feels like a pretty unlikely thing for someone to do? Also, I am not sure that the consequences of the mistake would be particularly negative/large.

**Comment by ErinBecker** [comment]
I don't have any objection to having the alumni listed in the same page, but think in that case the header for that section should be "ROLE Alumni" rather than "Current ROLE Alumni". Including the word "current" and "alumni" is confusing to me.

**Comment by froggleston** [comment]
I share the same view as Toby - a single page would be preferable, but agree that the search might end up being confusing, so perhaps a dedicated page for Alumni would be more explicit.

**Comment by elletjies** [comment]
I think a dedicated Alumni page would work better

**Comment by tobyhodges** [comment]
It seems that the majority preference is for separate pages. I have no strong opinion either way, so happy to go with that.

**Comment by sheraaronhurt** [comment]
I REALLY like the 1 page but I do understand the difficulty and can live with the 2 pages. Wondering if its possible to do something similar to like when you freeze the top row of the spreadsheet the term "Active" ROLE/ Alumni ROLE scrolls with it?

**Comment by maneesha** [comment]
I am going to keep this as two pages for now.  We can come back to this some other time with other ideas.
