### ISSUE TITLE
Order of items in "About" menu

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#95]
In the "About" menu, we list the following items:

* The Carpentries
* Impact
* Governance
* Team
* Careers
* Financials
* Contact us

What order should these items be in?

**Comment by maneesha** [comment]
@OscarSiba Please look at how the "About" menu is now. If it looks good to you, please say so here and close this issue. Otherwise you can leave a note about other changes we should make.

**Comment by OscarSiba** [comment]
I am also happy with this, thanks Maneesha.
