### ISSUE TITLE
What should go in page sidebars?

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#97]
On all pages that have a sidebar, we show these elements:

* Feedback on this page? Contact us (links to our Contact page)
* Edit this page on GitHub (links to that page in the GH repo)

On pages with multiple sections, we have a table of contents in the sidebar.

Optionally, we can also include the following elements in the sidebar:

* Newsletter subscribe button
* Last edited on <date>

For the two optional elements, what pages should we include them on?

**Comment by OscarSiba** [comment]
Please add only the newsletter subscribe bottom to the following pages:
- [ ] https://carp-new-website.netlify.app/blog/
- [ ] https://carp-new-website.netlify.app/community/
- [ ] https://carp-new-website.netlify.app/community/get-connected/
- [ ] https://carp-new-website.netlify.app/community/get-involved/

Please add both optional elements to these pages:
- [ ] https://carp-new-website.netlify.app/support/sponsorship/
- [ ] https://carp-new-website.netlify.app/support/membership/

**Comment by maneesha** [comment]
@OscarSiba to be clear, the four pages you have listed above are the only pages that the newsletter should be in the sidebar? (that is, it should be removed from all other pages?)

Likewise for the two pages that have both elements -- only those two pages should have both elements?

**Comment by OscarSiba** [comment]
No, the pages listed are the pages in which the the newsletter should be added to **in addition** to the pages that already have it in their sidebar. Same thing applies to the pages with both elements. So please do not remove it from anywhere else where those elements already exist.

**Comment by maneesha** [comment]
Note I misspoke - currently the only optional sidebar item is the newsletter.  I have added it as above.  If we want to consider other options for what goes in the sidebar, we can come back to this after launch.
